Feat/leonela
martindafonte/Fibonacci_Exercise pull request #11
Opened 2019-02-11 15:34 UTC by Leonela27

se completaron los Issues

2019-02-11 16:03 UTC, martindafonte commented
Hola @Leonela27 primero algunos comentarios sobre los nombres de los commits:
- Si el commit agrega un test debería comenzar con la palabra test.
- El commit inyección de dependencia no dice mucho, quizá es mejor: _implementa inyección de dependencia en web api_

2019-02-11 16:14 UTC, martindafonte requested changes

2019-02-11 16:14 UTC, martindafonte commented on README.md
> +el resultado de invocar el metodo CalcularFibonacci.
Si alguien lee la descripción del proyecto no va a saber que es el método CalcularFibonacci.
Tratá de explicar el proyecto pensando en alguien que nunca lo vió

2019-02-11 16:14 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +                return -1;
Se captura la excepción pero nunca se retorna al cliente o se registra en consola u otro Logger

2019-02-11 16:14 UTC, martindafonte commented on src/FibonacciWebApi/Services/Fibonacci.cs
> +        //OJO la implementacion de clases de una interfaz siempre es public
Borrar el comentario

2019-02-11 16:14 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FiboTest.cs
> +    public class FiboTest
A no ser que sea necesario, evitar las abreviaciones

2019-02-11 16:14 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FiboTest.cs
> +                int res = fib.CalcularFibonacci(-1);
Se puede hacer también con un Assert.ThrowsException(), pero está bien así

2019-02-11 16:14 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FibonacciControllerTest.cs
> +            int valorEsperado = fib.GetFibonacciMock();
No tiene sentido utilizar un Mock para obtener un valor esperado

2019-02-11 16:14 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FibonacciMock.cs
> +    class FibonacciMock
Un [https://en.wikipedia.org/wiki/Mock_object](Mock) debería implementar una interfaz, y suele utilizarse para obtener resultados predecibles y eliminar dependencias de otros módulos o componentes en test unitarios.

2019-02-11 16:19 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FiboTest.cs
> +            Assert.AreEqual(pasoBase_1, 1);
Fibonacci de 0 es 0
[https://en.wikipedia.org/wiki/Fibonacci_number](Link)

2019-02-11 16:25 UTC, Leonela27 commented on src/FibonacciWebApi/Services/Fibonacci.cs
> +        //OJO la implementacion de clases de una interfaz siempre es public
pronto

2019-02-11 16:36 UTC, Leonela27 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +                return -1;
se corrige mostrando un mensaje en consola y retornando null 
catch (Exception e)
            {
                Console.WriteLine("no es correcto invocar CalcularFibonacci de un negativo");
                return null;
            }

2019-02-11 17:27 UTC, Leonela27 commented on tests/FibonacciExcercise.UnitTests/FiboTest.cs
> +            Assert.AreEqual(pasoBase_1, 1);
pronto

2019-02-11 17:28 UTC, Leonela27 commented on tests/FibonacciExcercise.UnitTests/FiboTest.cs
> +    public class FiboTest
se modificò a FibonacciTest

2019-02-11 17:40 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +                return -1;
@Leonela27 me parece mejor retornar -1 y agregarlo en la documentación, o en todo caso retornar el mensaje de error.

2019-02-12 13:33 UTC, Leonela27 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +                return -1;
pronto, lo modifiqué retornando el mensaje de error

2019-08-19 14:41 UTC, closed without merging