Implementado servicio de calculo de fibonacci
martindafonte/Fibonacci_Exercise pull request #13
Opened 2019-08-20 17:35 UTC by gonzaguima

- Resuelve la suma de una secuencia de fibonacci para el número entero positivo ingresado
- Cuenta con tests unitarios y de integración
- Implementa inyección de dependencias
- Se modifica el Readme

2019-08-20 19:14 UTC, nhg1612 commented on README.md
> +El path de la url para utilizar la funcionalidad es http://localhost:<puerto>/api/fibo{valor-a-consultar}
El path de la url no coincide con la documentación (fibo{valor-a-consultar})

2019-08-20 19:15 UTC, nhg1612 commented on tests/FibonacciExcercise.UnitTests/FiboIntegrationTest.cs
> +        }
Estaría bueno agregar un test de integración para caso incorrecto

2019-08-20 19:21 UTC, nhg1612 commented
Hola @gonzaguima los commits 34f79fc como 49d19e8 deberían comenzar el prefijo test.

2019-08-20 19:59 UTC, nhg1612 commented on src/FibonacciWebApi/Controllers/FiboController.cs
> +            return res;
Se podría retornar directamente

2019-08-21 13:56 UTC, martindafonte requested changes

2019-08-21 13:56 UTC, martindafonte commented on README.md
> +Al devolver un tipo entero, el número máximo a calcular que devuelve valores correctos es el 47.
No condice la documentación con la implementación

2019-08-21 13:56 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FiboController.cs
> +         private readonly Services.IFiboService FiboService;
Las variables privadas utilizan camelCase, en general readonly utiliza un _ como prefijo

2019-08-21 13:56 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FiboController.cs
> +         public FiboController(Services.IFiboService pFiboService)
Parámetros utiliza camelCase, no se pone una p por delante

2019-08-21 13:56 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FiboIntegrationTest.cs
> +            Assert.IsTrue(httpResponse.IsSuccessStatusCode, "Código erroneo");
En el mensaje del assert está bueno incluir el código erroneo que dio, facilita al momento de diagnosticar errores

2019-08-21 13:56 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FiboIntegrationTest.cs
> +        public void IntegracionTest()
Agregar una invocación con algo que no sea un número para verificar que retorna un mensaje adecuado

2019-08-23 12:19 UTC, martindafonte approved these changes

2019-08-23 12:19 UTC, martindafonte commented
Excelente!

2019-08-23 12:19 UTC, closed without merging