Rfernandez
martindafonte/Fibonacci_Exercise pull request #14
Opened 2019-12-03 17:49 UTC by Romi92

Ejercicio inicial, fibonacci

2019-12-03 18:25 UTC, martindafonte requested changes
En general está todo muy bien, hay algunos detalles que marqué para mejorar o para considerar.

2019-12-03 18:25 UTC, martindafonte commented on FibonacciExcercise.IntegratedTest/FibonacciExcercise.IntegratedTest.csproj
> +    <PackageReference Include="coverlet.collector" Version="1.0.1" />
Para qué se usa este paquete?

2019-12-03 18:25 UTC, martindafonte commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.IsTrue(response.StatusCode == System.Net.HttpStatusCode.OK);
Esta comparación se debe hacer con Assert.AreEqual

2019-12-03 18:25 UTC, martindafonte commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.IsTrue(response.StatusCode == System.Net.HttpStatusCode.OK);
En caso de error debería retornar un StatusCode de 402 o similar

2019-12-03 18:25 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +        public ActionResult<string> Get(int numero)
Debería retornar un long

2019-12-03 18:25 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +                return "Debe ingresar un numero perteneciente al conjunto de los Naturales entre 0 y 90";
El mensaje de error se debería incluir junto con un tipo de respuesta BadRequest

2019-12-03 18:25 UTC, martindafonte commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +        //private int RealizarFibonacci(int fibo)
Eliminar código comentado

2019-12-03 18:25 UTC, martindafonte commented on src/FibonacciWebApi/Servicios/FibonacciServicios.cs
> +        public int RealizarFibonacci(int fibo)
Si el método solamente se debe utilizar en la clase, debería ser privado

2019-12-03 18:25 UTC, martindafonte commented on src/FibonacciWebApi/Servicios/FibonacciServicios.cs
> +                return -1;
Si valores menores a 0 no están soportados debería disparar una excepción

2019-12-03 18:25 UTC, martindafonte commented on tests/FibonacciExcercise.UnitTests/FibonacciTest.cs
> +        public void FibonacciTestPass()
Es mejor separar los test según el tipo de casos, por ejemplo Fibonacci_numero_negativo, Fibonacci_numeros_positivos, Fibonacci_casos_borde.

Cada uno de esos además se puede hacer con un DataTest

```
[TestMethod]
  [DataRow(1,2, DisplayName ="Sequential numbers")]
  [DataRow(2,2, DisplayName ="Equal numbers")]
  public void TestSomeNumbers (int x, int y)
  {
    Assert.AreEqual(x,y)       
  }
```

2019-12-03 18:29 UTC, papeserra requested changes

2019-12-03 18:29 UTC, papeserra commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +        public TestServer Server { get; set; }
Las propiedades que solo se utilizarán dentro de una clase deberían ser private

2019-12-03 18:29 UTC, papeserra commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            //Cliente.BaseAddress = new System.Uri();
Quitar codigo comentado que no será utilizado

2019-12-03 18:29 UTC, papeserra commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.AreEqual(data, "1");
Al utilizar un Assert.AreEqual el primer parámetro es el resultado esperado, el segundo el obtenido y luego opcionalmente se puede agregar un mensaje en caso de que falle

2019-12-03 18:29 UTC, papeserra commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.AreEqual(data, "Debe ingresar un numero perteneciente al conjunto de los Naturales entre 0 y 90");
Se puede utilizar constantes para los mensajes de error, hacen que dichos mensajes sean mas faciles de modificar a medida que se utilizan en mas lugares y comparar en los tests

2019-12-03 18:29 UTC, papeserra commented on README.md
> +
La descripción de un proyecto debería incluir información util para alguien que vaya trabajar con este. Es necesario explicar que tipo de aplicación es en este caso y una explicación de como usarlo

2019-12-03 18:29 UTC, papeserra commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +        //private int RealizarFibonacci(int fibo)
Quitar el codigo comentado que no se utiliza deja el codigo mas entendible

2019-12-03 18:29 UTC, papeserra commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +            if (numero < 0 || numero > 90)
La lógica de la aplicación debe estar contenida en el servicio, en este caso es CalcularFibonacci el encargado de saber que rango puede calcular

2019-12-03 18:29 UTC, papeserra commented on src/FibonacciWebApi/Servicios/FibonacciServicios.cs
> +        public int RealizarFibonacci(int fibo)
Dado que este método solo será utilizado dentro de la clase debería ser privado, asi no causar confusiones con el método que esperamos que se llame

2019-12-03 18:29 UTC, papeserra commented on tests/FibonacciExcercise.UnitTests/FibonacciTest.cs
> +        public void FibonacciTestPass()
Normalmente un test unitario debería probar un caso puntual, puede ser con varios valores. Por ejemplo estaría bueno dividir los casos exitosos en un test y un test para cada caso de error (intentar calcular un fibonacci fuera de rango por ejemplo)

2019-12-04 12:30 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciExcercise.IntegratedTest.csproj
> +    <PackageReference Include="coverlet.collector" Version="1.0.1" />
Me lo había solicitado mismo visual, pero lo quite y sigue funcionando.

2019-12-04 12:43 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.IsTrue(response.StatusCode == System.Net.HttpStatusCode.OK);
Quedaron cambiados todos los Assert.IsTrue por  Assert.AreEqual

2019-12-04 12:43 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.IsTrue(response.StatusCode == System.Net.HttpStatusCode.OK);
Quedó modificado.

2019-12-04 12:44 UTC, Romi92 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +        public ActionResult<string> Get(int numero)
Se cambio el retorno.

2019-12-04 12:44 UTC, Romi92 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +                return "Debe ingresar un numero perteneciente al conjunto de los Naturales entre 0 y 90";
Se cambio, se coloco Exceptions.

2019-12-04 12:44 UTC, Romi92 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +        //private int RealizarFibonacci(int fibo)
Código comentado eliminado.

2019-12-04 12:53 UTC, Romi92 commented on src/FibonacciWebApi/Servicios/FibonacciServicios.cs
> +        public int RealizarFibonacci(int fibo)
Quedó cambiado.

2019-12-04 12:53 UTC, Romi92 commented on src/FibonacciWebApi/Servicios/FibonacciServicios.cs
> +                return -1;
Los valores menos a 0 o mayores a 90, ahora disparan exceptions

2019-12-04 12:54 UTC, Romi92 commented on tests/FibonacciExcercise.UnitTests/FibonacciTest.cs
> +        public void FibonacciTestPass()
Modificado.

2019-12-04 12:54 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +        public TestServer Server { get; set; }
Cambie las prop a private.

2019-12-04 12:54 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            //Cliente.BaseAddress = new System.Uri();
Todo el código comentado, fue eliminado.

2019-12-04 12:55 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.AreEqual(data, "1");
Quedaron cambiados todos los Assert.IsTrue por Assert.AreEqual. Y el orden.

2019-12-04 12:55 UTC, Romi92 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +        //private int RealizarFibonacci(int fibo)
El código comentado fue eliminado.

2019-12-04 12:56 UTC, Romi92 commented on src/FibonacciWebApi/Controllers/FibonacciController.cs
> +            if (numero < 0 || numero > 90)
Se hizo el cambio.

2019-12-04 12:57 UTC, Romi92 commented on src/FibonacciWebApi/Servicios/FibonacciServicios.cs
> +        public int RealizarFibonacci(int fibo)
Se el método a privado.

2019-12-04 12:57 UTC, Romi92 commented on tests/FibonacciExcercise.UnitTests/FibonacciTest.cs
> +        public void FibonacciTestPass()
Se arregló

2019-12-04 13:22 UTC, Romi92 commented on FibonacciExcercise.IntegratedTest/FibonacciTestIntegracion.cs
> +            Assert.AreEqual(data, "Debe ingresar un numero perteneciente al conjunto de los Naturales entre 0 y 90");
Se cambio para constantes.

2019-12-04 13:22 UTC, Romi92 commented on README.md
> +
Se modifico la descripción del proyecto.

2019-12-04 13:44 UTC, martindafonte approved these changes

2019-12-04 13:45 UTC, closed without merging